# Generated by Django 5.2.1 on 2025-05-13 19:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_image_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
