# Generated by Django 5.2.1 on 2025-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articletranslation_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legenda da imagem'),
        ),
    ]
